name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest npm
        run: npm install npm@latest

      - name: Install dependencies
        run: npm ci

  build-image:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate a config.json
        run: |
          cat <<JSON > config.json
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n 'june07:${{ secrets.GITHUB_TOKEN }}' | base64)"
              }
            }
          }
          JSON
          ls -lah config.json
          cat config.json
      - name: Build and Push Docker Image
        run: |
          docker run \
          -v $(pwd):/workspace \
          -v $(pwd)/config.json:/kaniko/.docker/config.json:ro \
          gcr.io/kaniko-project/executor:latest \
          --context dir:///workspace/ \
          --dockerfile Dockerfile \
          --destination ghcr.io/${GITHUB_REPOSITORY}/api-${{ github.sha }} \
          --destination ghcr.io/${GITHUB_REPOSITORY}/api-latest

  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Install SSH Client
        run: sudo apt update && sudo apt install -y openssh-client

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 400 ~/.ssh/deploy_key
          ssh-keyscan -H swarm.june07.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

      - name: Deploy to Production
        run: ssh -i ~/.ssh/deploy_key github@swarm.june07.com \
          /home/github/june07/aname/backend/update-service.sh ghcr.io/${GITHUB_REPOSITORY}/api-${{ github.sha }} aname-backend_node
